#!/usr/bin/env python3
"""
Emit userspace/ml-aed/ml-aed-exptable.h from the vendor AE exposure table.

Source: the sensor tuning blob at offset 0xb6524, 366 entries of
{exp_tbl_val u32 (gain Q8), line_count u32}. This is shipped configuration for
the fixed FPV preview mode (1080p60, limit_line_count 1125, gain_max 64.0), not
something the vendor computes: the generator body at 0x2649f4 does not emit it.

The table was previously read out of a live heap dump at 0x9c4808, which is the
AEC state block's runtime copy of these same bytes; the two were compared entry
by entry and agree over all 366. The blob is used instead because it is the
configuration the driver already loads, so the table cannot drift from the file
the ISP is tuned by, and regenerating needs no capture session.

Checks before emitting:
- entry 0 is (256, 1) and entry 365 is (16328, 1125)
- the two capture operating points: entry 317 = (3938, 1125), 283 = (1432, 1125)
- line_count is monotone non-decreasing, pinned at 1125 from entry 227 on
- within every line_count plateau, exp_tbl_val steps by ceil(prev * 1.03)
"""

import math
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TUNING = ROOT / "firmware/bin/slot-a/usr/usrdata/tunning/nt99235_tuning_preview_fpv.bin"
OUT = ROOT / "userspace/ml-aed/ml-aed-exptable.h"
OFF = 0xB6524
COUNT = 366


def load() -> list[tuple[int, int]]:
    blob = TUNING.read_bytes()
    return [struct.unpack_from("<II", blob, OFF + 8 * i) for i in range(COUNT)]


def check(tbl: list[tuple[int, int]]) -> None:
    assert tbl[0] == (256, 1), tbl[0]
    assert tbl[365] == (16328, 1125), tbl[365]
    assert tbl[317] == (3938, 1125), tbl[317]
    assert tbl[283] == (1432, 1125), tbl[283]
    for i in range(1, COUNT):
        assert tbl[i][1] >= tbl[i - 1][1], f"line_count dips at {i}"

    assert all(lc == 1125 for _, lc in tbl[227:]), "pin broken"
    for i in range(1, COUNT):
        if tbl[i][1] == tbl[i - 1][1]:
            want = math.ceil(tbl[i - 1][0] * 1.03)
            assert tbl[i][0] == want, f"plateau chain breaks at {i}: {tbl[i][0]} != {want}"


def emit(tbl: list[tuple[int, int]]) -> str:
    rows = []
    for i in range(0, COUNT, 4):
        cells = ", ".join(f"{{{v}, {lc}}}" for v, lc in tbl[i : i + 4])
        rows.append(f"    {cells},")

    body = "\n".join(rows)
    return f"""\
/*
 * Vendor AE exposure table, read from the sensor tuning blob at 0xb6524, the
 * same file the ISP driver request_firmware()s: 366 entries of {{gain Q8, line_count}}
 * for the FPV preview mode, 1080p60, exposure ceiling one frame (1125 lines),
 * gain ceiling 64.0. exp_index walks this table; the exposure/gain split is a
 * property of the table. exp_tbl_val / 256 is also the ladder abscissa
 * (table[317] = 3938 and table[283] = 1432 are the two validated operating
 * points). Generated by glue/camera/gen-ae-exptable.py; do not edit.
 */
#ifndef ML_AED_EXPTABLE_H
#define ML_AED_EXPTABLE_H

#include <stdint.h>

#define MLAED_EXP_TABLE_LEN {COUNT}

struct mlaed_exp_entry {{
    uint32_t gain_q8;
    uint32_t line_count;
}};

static const struct mlaed_exp_entry mlaed_exp_table[MLAED_EXP_TABLE_LEN] = {{
{body}
}};

#endif
"""


def main() -> int:
    tbl = load()
    check(tbl)
    OUT.write_text(emit(tbl))
    print(f"wrote {OUT} ({COUNT} entries, all checks passed)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
