#!/usr/bin/env python3
"""Emit native/ml-3a-exptable.h from the vendor AE exposure table.

Source: out/au-vendor-session/heap-live.bin, the AE state block's generated
exposure table at heap offset 0x9c4808 (state 0x9c47a0 + 0x68), 366 entries of
{exp_tbl_val u32 (gain Q8), line_count u32}. The table is measured vendor
output for the fixed FPV preview configuration (1080p60, limit_line_count
1125, gain_max 64.0); the generator body at 0x2649f4 provably did not emit it
(hdf-075), so the table is carried as data, not regenerated.

Checks before emitting:
- entry 0 is (256, 1) and entry 365 is (16328, 1125)
- the two capture operating points: entry 317 = (3938, 1125), 283 = (1432, 1125)
- line_count is monotone non-decreasing, pinned at 1125 from entry 227 on
- within every line_count plateau, exp_tbl_val steps by ceil(prev * 1.03)
"""

import math
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEAP = ROOT / "out/au-vendor-session/heap-live.bin"
OUT = ROOT / "native/ml-3a-exptable.h"
OFF = 0x9C4808
COUNT = 366


def load() -> list[tuple[int, int]]:
    blob = HEAP.read_bytes()
    return [struct.unpack_from("<II", blob, OFF + 8 * i) for i in range(COUNT)]


def check(tbl: list[tuple[int, int]]) -> None:
    assert tbl[0] == (256, 1), tbl[0]
    assert tbl[365] == (16328, 1125), tbl[365]
    assert tbl[317] == (3938, 1125), tbl[317]
    assert tbl[283] == (1432, 1125), tbl[283]
    for i in range(1, COUNT):
        assert tbl[i][1] >= tbl[i - 1][1], f"line_count dips at {i}"
    assert all(lc == 1125 for _, lc in tbl[227:]), "pin broken"
    for i in range(1, COUNT):
        if tbl[i][1] == tbl[i - 1][1]:
            want = math.ceil(tbl[i - 1][0] * 1.03)
            assert tbl[i][0] == want, f"plateau chain breaks at {i}: {tbl[i][0]} != {want}"


def emit(tbl: list[tuple[int, int]]) -> str:
    rows = []
    for i in range(0, COUNT, 4):
        cells = ", ".join(f"{{{v}, {lc}}}" for v, lc in tbl[i : i + 4])
        rows.append(f"    {cells},")
    body = "\n".join(rows)
    return f"""\
/*
 * Vendor AE exposure table, measured from the running stock stack
 * (heap-live.bin + 0x9c4808, hdf-075): 366 entries of {{gain Q8, line_count}}
 * for the FPV preview mode, 1080p60, exposure ceiling one frame (1125 lines),
 * gain ceiling 64.0. exp_index walks this table; the exposure/gain split is a
 * property of the table. exp_tbl_val / 256 is also the ladder abscissa
 * (table[317] = 3938 and table[283] = 1432 are the two validated operating
 * points). Generated by glue/camera/gen-ae-exptable.py; do not edit.
 */
#ifndef ML_3A_EXPTABLE_H
#define ML_3A_EXPTABLE_H

#include <stdint.h>

#define ML3A_EXP_TABLE_LEN {COUNT}

struct ml3a_exp_entry {{
    uint32_t gain_q8;
    uint32_t line_count;
}};

static const struct ml3a_exp_entry ml3a_exp_table[ML3A_EXP_TABLE_LEN] = {{
{body}
}};

#endif
"""


def main() -> int:
    tbl = load()
    check(tbl)
    OUT.write_text(emit(tbl))
    print(f"wrote {OUT} ({COUNT} entries, all checks passed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
