#!/bin/sh
# MissingLynk boot hook (auto-generated by `missinglynk install`).
# run.sh runs this every boot (then exits), so we apply enabled components and
# then run the stock boot body (copied verbatim from @RUN_SH@, below). usb0 + SSH
# always come up. Persistent: this file stays in place, no re-arm. No `set -e`,
# component actions are best-effort.
ML=@ML_DIR@
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:$PATH

# escape hatch: hold @SKIP_LABEL@ at power-on to skip MissingLynk for this boot
# (temporary stock boot; config is untouched, the next boot applies normally).
# Read the adc-keys voltage ladder directly (instant, no input-driver poll delay):
# @SKIP_LABEL@ pulls ADC ch0 to ~400mV; the @SKIP_MV_MIN@-@SKIP_MV_MAX@mV window
# isolates it from idle (0mV) and neighbours. Decision logged to lastboot.log.
@OFF_INIT@
mv=$(cat @SKIP_ADC@ 2>/dev/null || echo 0)
if [ "$mv" -ge @SKIP_MV_MIN@ ] && [ "$mv" -le @SKIP_MV_MAX@ ]; then
    echo "MissingLynk: @SKIP_LABEL@ held at boot (ADC $mv mV), skipping components this boot"
    echo "boot: adc=$mv skip=y" > "$ML/lastboot.log"
    skip=y
else
    echo "boot: adc=$mv skip=n" > "$ML/lastboot.log"
    skip=n
@DEFAULTS@
    [ -f "$ML/config" ] && . "$ML/config"
fi

# record what this boot applies (status diffs the config against it to flag
# settings changed since boot as "needs reboot to apply")
@SNAPSHOT@

# component bind-mounts (before the body starts ar_lowdelay)
@BIND_MOUNTS@

# menu: the binary lives on the SD (too big for /usrdata); copy it to tmpfs and
# bind-mount it over the stock UI app so start_fb.sh launches our menu.
# No SD / no file -> stock menu.
[ "$menu" = on ] && [ -f "@SD_MENU_BIN@" ] && { cp "@SD_MENU_BIN@" "@TMP_MENU@" && chmod +x "@TMP_MENU@" && mount -o bind "@TMP_MENU@" "@MENU_TARGET@"; } 2>/dev/null

# indicator HUD: wait for the UI app, then draw "MissingLynk" + each enabled
# component, repeated briefly so it survives the UI's initial redraws
if [ "$indicator" = on ]; then
    (
        n=0
        while [ $n -lt 60 ] && ! pidof @OSD_APP@ >/dev/null 2>&1; do sleep 1; n=$((n + 1)); done
        sleep @INDICATOR_SETTLE@
        k=0
        while [ $k -lt @INDICATOR_REPEAT@ ]; do
            x=@HUD_X@; y=@HUD_Y@
            "$ML/bin/fbtext" "MissingLynk" $x $y @HUD_TITLE_PX@
            y=$((y + @HUD_TITLE_STEP@))
@HUD_LINES@
            sleep 1
            k=$((k + 1))
        done
    ) &
fi

# Stock boot body (verbatim from @RUN_SH@)
@BOOT_BODY@
@ECM_BLOCK@

# component daemons (launched after the boot body)
@DAEMONS@

# on-goggle menu (always on for normal boots; long-press RIGHT to open).
# Skipped on a recovery boot (escape hatch) so the boot stays fully stock.
[ "$skip" = n ] && setsid "$ML/bin/mlmenu" >/dev/null 2>&1 &
